// Weapon Categories
#define RND_CATEGORY_WEAPONS "/Оружие"
#define RND_SUBCATEGORY_WEAPONS_FIRING_PINS "/Ударники"
#define RND_SUBCATEGORY_WEAPONS_AMMO "/Боеприпасы"
#define RND_SUBCATEGORY_WEAPONS_PARTS "/Детали оружия"
#define RND_SUBCATEGORY_WEAPONS_RANGED "/Дальнобойное оружие"
#define RND_SUBCATEGORY_WEAPONS_MELEE "/Оружие ближнего боя"
#define RND_SUBCATEGORY_WEAPONS_KITS "/Наборы сборки оружия"

// Wiremod Categories
#define RND_CATEGORY_CIRCUITRY "/Схемотехника"
#define RND_CATEGORY_CIRCUITRY_CORE "/Ядро"
#define RND_SUBCATEGORY_CIRCUITRY_COMPONENTS "/Компоненты схем"
#define RND_SUBCATEGORY_CIRCUITRY_BCI_COMPONENTS "/Компоненты нейроинтерфейса"
#define RND_SUBCATEGORY_CIRCUITRY_SHELLS "/Оболочки схем"

// Tool Categories
#define RND_CATEGORY_TOOLS "/Инструменты"
#define RND_SUBCATEGORY_TOOLS_MEDICAL "/Медицинские инструменты"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ADVANCED "/Медицинские инструменты (продвинутые)"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ALIEN "/Медицинские инструменты (инопланетные)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING "/Инженерные инструменты"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ADVANCED "/Инженерные инструменты (продвинутые)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ALIEN "/Инженерные инструменты (инопланетные)"
#define RND_SUBCATEGORY_TOOLS_SERVICE "/Сервисные инструменты"
#define RND_SUBCATEGORY_TOOLS_BOTANY "/Ботанические инструменты"
#define RND_SUBCATEGORY_TOOLS_BOTANY_ADVANCED "/Ботанические инструменты (продвинутые)"
#define RND_SUBCATEGORY_TOOLS_JANITORIAL "/Уборочные инструменты"
#define RND_SUBCATEGORY_TOOLS_PLUMBING "/Сантехнические инструменты"
#define RND_SUBCATEGORY_TOOLS_ATMOSPHERICS "/Атмосферные инструменты"
#define RND_SUBCATEGORY_TOOLS_MINING "/Шахтерские инструменты"
#define RND_SUBCATEGORY_TOOLS_CARGO "/Инструменты снабжения"
#define RND_SUBCATEGORY_TOOLS_PKA_MODS "/Модули ПКУ"
#define RND_SUBCATEGORY_TOOLS_SECURITY "/Инструменты службы безопасности"
#define RND_SUBCATEGORY_TOOLS_MISC "/Прочие инструменты"

#define RND_CATEGORY_CONSTRUCTION "/Строительство"
#define RND_SUBCATEGORY_CONSTRUCTION_MOUNTS "/Каркасы и крепления"
#define RND_SUBCATEGORY_CONSTRUCTION_ELECTRONICS "/Электроника"
#define RND_SUBCATEGORY_CONSTRUCTION_MACHINERY "/Машины"
#define RND_SUBCATEGORY_CONSTRUCTION_MATERIALS "/Материалы и сплавы"
#define RND_SUBCATEGORY_CONSTRUCTION_LIGHTING "/Освещение"
#define RND_SUBCATEGORY_CONSTRUCTION_ASSEMBLIES "/Электрические сборки"

#define RND_CATEGORY_COMPUTER "/Компьютерные платы"
#define RND_SUBCATEGORY_COMPUTER_ENTERTAINMENT "/Сервисные консоли"
#define RND_SUBCATEGORY_COMPUTER_MEDICAL "/Медицинские консоли"
#define RND_SUBCATEGORY_COMPUTER_ROBOTICS "/Консоли робототехники"
#define RND_SUBCATEGORY_COMPUTER_GENETICS "/Консоли генетики"
#define RND_SUBCATEGORY_COMPUTER_RECORDS "/Консоли записей"
#define RND_SUBCATEGORY_COMPUTER_COMMAND "/Командные консоли"
#define RND_SUBCATEGORY_COMPUTER_SECURITY "/Консоли службы безопасности"
#define RND_SUBCATEGORY_COMPUTER_RESEARCH "/Исследовательские консоли"
#define RND_SUBCATEGORY_COMPUTER_ENGINEERING "/Инженерные и атмосферные консоли"
#define RND_SUBCATEGORY_COMPUTER_CARGO "/Консоли снабжения"

#define RND_CATEGORY_MACHINE "/Платы машин"
#define RND_SUBCATEGORY_MACHINE_ATMOS "/Атмосферные машины"
#define RND_SUBCATEGORY_MACHINE_KITCHEN "/Кухонные машины"
#define RND_SUBCATEGORY_MACHINE_BAR "/Барные машины"
#define RND_SUBCATEGORY_MACHINE_BOTANY "/Ботанические машины"
#define RND_SUBCATEGORY_MACHINE_ENGINEERING "/Инженерные машины"
#define RND_SUBCATEGORY_MACHINE_RESEARCH "/Исследовательские машины"
#define RND_SUBCATEGORY_MACHINE_MEDICAL "/Медицинские машины"
#define RND_SUBCATEGORY_MACHINE_CHEMISTRY "/Химические машины"
#define RND_SUBCATEGORY_MACHINE_SECURITY "/Машины службы безопасности"
#define RND_SUBCATEGORY_MACHINE_CARGO "/Машины снабжения"
#define RND_SUBCATEGORY_MACHINE_TELEPORT "/Телепортационные машины"
#define RND_SUBCATEGORY_MACHINE_ROBOTICS "/Машины робототехники"
#define RND_SUBCATEGORY_MACHINE_GENETICS "/Генетические машины"
#define RND_SUBCATEGORY_MACHINE_FAB "/Фабрикаторы"
#define RND_SUBCATEGORY_MACHINE_SERVICE "/Сервисные машины"
#define RND_SUBCATEGORY_MACHINE_TELECOMMS "/Телекоммуникационные машины"

#define RND_CATEGORY_EQUIPMENT "/Снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_SERVICE "/Сервисное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_JOKE "/Совершенно секретное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_CHEMISTRY "/Химическое снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_MEDICAL "/Медицинское снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_SECURITY "/Снаряжение службы безопасности"
#define RND_SUBCATEGORY_EQUIPMENT_TELECOMMS "/Снаряжение связи"
#define RND_SUBCATEGORY_EQUIPMENT_BLUESPACE "/Блюспейс-снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_ENGINEERING "/Инженерное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_ATMOSPHERICS "/Атмосферное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_SCIENCE "/Научное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_GAS_TANKS "/Газовые баллоны"
#define RND_SUBCATEGORY_EQUIPMENT_GAS_TANKS_EQUIPMENT "/Оснастка газовых баллонов"
#define RND_SUBCATEGORY_EQUIPMENT_XENOBIOLOGY "/Ксенобиологическое снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_GENETICS "/Генетическое снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_JANITOR "/Уборочное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_KITCHEN "/Барное и кухонное снаряжение"
#define RND_SUBCATEGORY_EQUIPMENT_MISC "/Прочее снаряжение"

#define RND_CATEGORY_AI "/Искусственный интеллект"
#define RND_SUBCATEGORY_AI_CORE "/Сборка ИИ"
#define RND_SUBCATEGORY_AI_CORE_MODULES "/Основные модули ИИ"
#define RND_SUBCATEGORY_AI_DANGEROUS_MODULES "/Опасные модули ИИ"
#define RND_SUBCATEGORY_AI_LAW_MANIPULATION "/Изменение законов ИИ"
#define RND_SUBCATEGORY_AI_MISC "/Прочие предметы ИИ"
#define RND_SUBCATEGORY_AI_UPGRADES "/Улучшения ИИ"

#define RND_CATEGORY_MODULAR_COMPUTERS "/Модульные компьютеры"
#define RND_SUBCATEGORY_MODULAR_COMPUTERS_FRAMES "/Корпуса"
#define RND_SUBCATEGORY_MODULAR_COMPUTERS_PARTS "/Детали"

#define RND_CATEGORY_STOCK_PARTS "/Стоковые детали"
#define RND_SUBCATEGORY_STOCK_PARTS_MISC "/Прочие детали"
#define RND_SUBCATEGORY_STOCK_PARTS_TURBINE "/Детали турбин"
#define RND_SUBCATEGORY_STOCK_PARTS_TELECOMMS "/Детали телекоммуникаций"
#define RND_SUBCATEGORY_STOCK_PARTS_1 "/Детали 1 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_2 "/Детали 2 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_3 "/Детали 3 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_4 "/Детали 4 уровня"
#define RND_SUBCATEGORY_STOCK_PARTS_EXCHANGERS "/Обменные устройства"

#define RND_CATEGORY_SYNDICATE "/Нелегальные чертежи"

#define RND_CATEGORY_EXOSUIT_BOARDS "/Платы экзокостюмов"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_RIPLEY "/Ripley"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_ODYSSEUS "/Odysseus"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_GYGAX "/Gygax"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_DURAND "/Durand"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_HONK "/H.O.N.K."
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_PHAZON "/Phazon"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_CLARKE "/Clarke"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_SAVANNAH_IVANOV "/Savannah-Ivanov"

#define RND_CATEGORY_MECHFAB_RIPLEY "/Ripley"
#define RND_CATEGORY_MECHFAB_PADDY "/Paddy"
#define RND_CATEGORY_MECHFAB_ODYSSEUS "/Odysseus"
#define RND_CATEGORY_MECHFAB_GYGAX "/Gygax"
#define RND_CATEGORY_MECHFAB_DURAND "/Durand"
#define RND_CATEGORY_MECHFAB_HONK "/H.O.N.K."
#define RND_CATEGORY_MECHFAB_PHAZON "/Phazon"
#define RND_CATEGORY_MECHFAB_CLARKE "/Clarke"
#define RND_CATEGORY_MECHFAB_SAVANNAH_IVANOV "/Savannah-Ivanov"
#define RND_SUBCATEGORY_MECHFAB_CHASSIS "/Шасси"
#define RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT "/Поддерживаемое снаряжение"
#define RND_SUBCATEGORY_MECHFAB_CONTROL_INTERFACES "/Интерфейсы управления"

#define RND_CATEGORY_MECHFAB_EQUIPMENT "/Снаряжение экзокостюмов"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MINING "/Шахтерское снаряжение"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_WEAPONS "/Оружие и боеприпасы"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MODULES "/Броня и ремонтные модули"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MISC "/Прочее"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MEDICAL "/Медицинское"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_HONK "/Клоунские чертежи"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_CONTROL_INTERFACES "/Интерфейсы управления"

#define RND_CATEGORY_MECHFAB_CYBORG "/Киборг"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS "/Шасси киборгов"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_COMPONENTS "/Компоненты"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CELLS "/Батареи"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CONTROL_INTERFACES "/Интерфейсы управления"

#define RND_CATEGORY_MECHFAB_CYBORG_MODULES "/Модули киборгов"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ALL "/Все киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MEDICAL "/Медицинские киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ENGINEERING "/Инженерные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_JANITOR "/Уборочные киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_SECURITY "/Киборги службы безопасности"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MINING "/Шахтерские киборги"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_SERVICE "/Сервисные киборги"

#define RND_CATEGORY_MODSUITS "/MOD-костюмы"
#define RND_SUBCATEGORY_MODUITS_CHASSIS "/Шасси"
#define RND_SUBCATEGORY_MODSUITS_PLATING "/Пластины"
#define RND_SUBCATEGORY_MODSUITS_MISC "/Прочее"

#define RND_CATEGORY_MODSUIT_MODULES "/MOD-модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_GENERAL "/Общие модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_ENGINEERING "/Инженерные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_MEDICAL "/Медицинские модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SCIENCE "/Научные модули"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SECURITY "/Модули службы безопасности"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SUPPLY "/Модули снабжения"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SERVICE "/Сервисные модули"

#define RND_CATEGORY_CYBERNETICS "/Кибернетика"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_1 "/Кибернетические органы 1 уровня"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_2 "/Кибернетические органы 2 уровня"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_3 "/Кибернетические органы 3 уровня"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_COMBAT "/Боевые кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS_MISC "/Прочие кибернетические органы"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_COMBAT "/Боевые кибернетические импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_HEALTH "/Медицинские кибернетические импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_TOOLS "/Инструменты имплантации"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_UTILITY "/Утилитарные кибернетические импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_MISC "/Прочие кибернетические импланты"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS_SECURITY "/Кибернетические импланты службы безопасности"
#define RND_SUBCATEGORY_CYBERNETICS_ADVANCED_LIMBS "/Продвинутые кибернетические конечности"

// Limb Categories
#define RND_CATEGORY_LIMBS_DIGITIGRADE "digitigrade"
#define RND_CATEGORY_LIMBS_OTHER "Прочие конечности"

/// Biogenerator Categories
#define RND_CATEGORY_BIO_FOOD "Еда"
#define RND_CATEGORY_BIO_CHEMICALS "Химикаты"
#define RND_CATEGORY_BIO_MATERIALS "Материалы"

// Meta categories
#define RND_CATEGORY_INITIAL "initial"
#define RND_CATEGORY_HACKED "hacked"
#define RND_CATEGORY_IMPORTED "/Импортированные чертежи"
